### ISSUE TITLE
GPU memory occupation

### ISSUE THREAD

**Issue by yelantf** [renatoviolin/electra-squad-8#2]
@renatoviolin Thanks for sharing your nice work! I am here to seek for some help. Did you ever encounter an OOM error when using electra-large model? I tried it on a 12-GB GPU(fine-tune on CoLA dataset), but an OOM error always raises even with train_batch_size set as 1. Could you tell me how did you get this work? Many thanks!

**Comment by renatoviolin** [comment]
Hi @yelantingfeng 
In fact and don't experienced this OOM. Are you using my modifications? As described in the repo, I use the following adjusts:
- reduce batch size to 4 (original is 32)
- use mixed precision to slight reduce the memory consumption.
- freeze 2/3 of the network and train the last 8 layers (layer 16 to 23).

Any value greater than those above give me OOM in 8GB GPU

**Comment by yelantf** [comment]
Thanks for the informative reply! I was trying the official implementation as a quick start and found your repository just now. I would try your modifications then, thank you!
